#!/bin/sh

xrdb -merge $HOME/.Xresources
#xrandr --dpi 183 --fb 7152x3840 \
  #--output DP-2.8 --mode 1920x2160 --pos 0x1920 \
  #--output DP-2.9 --mode 1920x2160 \
  #--output DP-4 --scale 1.3x1.3 --mode 3840x2160 --pos 2160x805
xscreensaver &
# workaround flatpack bug https://github.com/flatpak/xdg-desktop-portal-gtk/issues/72
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
case $HOSTNAME in
  (daltigoth) feh --no-fehbg --bg-scale ~/backgrounds/current.jpg;;
  (sven-uni)   feh --no-fehbg --bg-center ~/backgrounds/current-left.jpg ~/backgrounds/current-right.jpg;;
esac
#setxkbmap -layout "us, de" -option "grp:caps_toggle"
setxkbmap -layout "us"
#xmodmap -e "keycode 134 = Tab Delete"
xmodmap ~/.dotfiles/Xmodmap_model01
#xinput set-prop "Wacom Bamboo Connect Pen stylus" --type=float "Coordinate Transformation Matrix" 0.5 0 0.5 0 1 0 0 0 1
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
dropbox-cli start
kitty --session ~/.dotfiles/kitty-session.conf &
firefox &
#thunderbird &
#pidgin &
#kupfer &
emacs &
dunst -conf ~/.dunstrc &
udiskie &
# remap Delete to Tab (and Shift-Delete to Delete)
$HOME/bin/ergo
$HOME/phone.sh
exec xmonad
#exec metacity
#exec dwm
#exec fvwm
